### ISSUE TITLE
VPOT Prioritisation - genotype IndexError: list index out of range

### ISSUE THREAD

**Issue by illarionovaanastasia** [VCCRI/VPOT#4]
Hi! 
I would like to use VPOT to prioritize variants in my dataset which were annotated with VEP. I have successfully run the convertVEP step, however while submitting the converted vcf into the VPOT Prioritisation step I am getting the following error:
`#VPOT version 2 - 07/01/2021 
VPOT Prioritisation - Main
Samples input files :  sample_list.tsv
vcf
VPOT: Parameter file supplied
QC MaxCOverage :  0
QC Hete_balance :  0
QC Genotype_Quality :  0
VS Score Threshold :  0
ppf.txt
processing input file :  ['data.vcf', 'sample1', '']
Traceback (most recent call last):
  File "../VPOT.py", line 177, in <module>
    main() 
  File "../VPOT.py", line 135, in main
    VPOT_1_prioritise.main() #
  File "~/VPOT/VPOT_1_prioritise.py", line 299, in main
    error=VPOT_1_1_VCF.read_variant_source_file() #
  File "~/VPOT/VPOT_1_1_VCF.py", line 178, in read_variant_source_file
    work_this_src_file(this_line)  #
  File "~/VPOT/VPOT_1_1_VCF.py", line 401, in work_this_src_file
    work_this_src_file_1(source_vcf,wrkf1) #
  File "~/VPOT/VPOT_1_1_VCF.py", line 379, in work_this_src_file_1
    check_this_variant(src_line, wrkf1) #
  File "~/VPOT/VPOT_1_1_VCF.py", line 433, in check_this_variant
    elif (GENOTYPE1[0] == GENOTYPE1[1]) : # a homozygous alt genotype 
IndexError: list index out of range`

It seems that the issue arises during the parsing of sample genotypes. I would appreciate a lot any hints of how to tackle this problem!

Best,

Anastasia

**Comment by croct** [comment]
Thanks for your question about VPOT Anastasia,

Would it be possible for you to send me some test data (just a small subset) that reproduces this problem - along with commands & other configuration files for VPOT (ppf) that you used?

You can send them to `m<dot>troup<at>victorchang<dot>edu<dot>au`

Michael

**Comment by illarionovaanastasia** [comment]
Dear Michael,

Thank you for your promt reply. I have sent you the files and the command to replicate the issue.

best,

Anastasia

**Comment by croct** [comment]
Thanks for the sample data.   I was able to reproduce your problem, which was caused by VPOT not allowing for phased genotypes (e.g. 0|1 instead of the normal 0/1).  I have applied a change that now allows for phased genotyptes.  Pull the latest changes to this repository to get access to the change.

**Comment by illarionovaanastasia** [comment]
The Priority Option is working now without any issues. 
Thank you!
