### ISSUE TITLE
IndexError: list index out of range 

### ISSUE THREAD

**Issue by sturkistany** [VCCRI/VPOT#5]
Hi 

I am using VPOT and its working very well except for  multiple vcfs . Please see the error message below 
[sturkistany@kdata1 test5]$ python3 ../VPOT.py priority testout_$vcf_f test_VCF_sample_Rabie_I_HD99_S28.txt  default_0.001_variants_parameters_PPF.txt
#VPOT version 2 - 07/01/2021
VPOT Prioritisation - Main
Samples input files :  test_VCF_sample_Rabie_I_HD99_S28.txt
vcf
VPOT: Parameter file supplied
QC MaxCOverage :  0
QC Hete_balance :  0
QC Genotype_Quality :  0
VS Score Threshold :  0
default_0.001_variants_parameters_PPF.txt
processing input file :  ['Rabie_I_HD99_S28.vcf', 'Rabie_I_HD99_S28', '']
Traceback (most recent call last):
  File "../VPOT.py", line 177, in <module>
    main()
  File "../VPOT.py", line 135, in main
    VPOT_1_prioritise.main() #
  File "/fefs1/cegmr/sturkistany/VPOT-master/VPOT_1_prioritise.py", line 299, in main
    error=VPOT_1_1_VCF.read_variant_source_file() #
  File "/fefs1/cegmr/sturkistany/VPOT-master/VPOT_1_1_VCF.py", line 178, in read_variant_source_file
    work_this_src_file(this_line)  #
  File "/fefs1/cegmr/sturkistany/VPOT-master/VPOT_1_1_VCF.py", line 401, in work_this_src_file
    work_this_src_file_1(source_vcf,wrkf1) #
  File "/fefs1/cegmr/sturkistany/VPOT-master/VPOT_1_1_VCF.py", line 379, in work_this_src_file_1
    check_this_variant(src_line, wrkf1) #
  File "/fefs1/cegmr/sturkistany/VPOT-master/VPOT_1_1_VCF.py", line 433, in check_this_variant
    elif (GENOTYPE1[0] == GENOTYPE1[1]) : # a homozygous alt genotype
IndexError: list index out of range

not sure what is the problem here, Please let me know how i can overcome this? 

Shereen

**Comment by eipVCCRI** [comment]
Hi Shereen,

Thank you for your interest in VPOT.

With this error, it usually is some variation in the source input sample file.

Could you possibly send us a small sample of the Rabie_I_HD99_S28.vcf for us to run? It would also be helpful if you can send the PPF file you are using, and input test_VCF_sample_Rabie_I_HD99_S28.txt, so we can replicate your run conditions.

Thanks and I hope we can resolve your problem.
Eddie

**Comment by eipVCCRI** [comment]
Shereen,

You might also try downloading the latest version of VPOT, which was updated in Sept to resolve phased genotype in the VCF. 

Eddie

**Comment by sturkistany** [comment]
Thanks Eddie !

I have downloaded the updated version and it worked great with me .

**Comment by eipVCCRI** [comment]
Good to hear. 

You also mentioned you have problems with multiple vcfs in the initial post. Do you still have that problem?

Eddie

**Comment by eipVCCRI** [comment]
Closing issue as posted problem is now resolved.
